### ISSUE TITLE
Swift package manager can't build on Xcode 10.2 anymore

### ISSUE THREAD

**Issue by ChiellieNL** [Alamofire/Alamofire#2761]
* [X] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## What did you do?

Updated from Xcode 10.1 to Xcode 10.2 (which became available per today)

## What did you expect to happen?

I could run swift build and/or swift generate-xcodeproj without errors

## What happened instead?

Xcode couldn't build Alamofire due to a manifest error:
```
https://github.com/Alamofire/Alamofire.git @ 4.8.1: error: manifest parse error(s):
/var/folders/5_/bn8g0cbj2q5_ng_dp9m2lkbr0000gn/T/TemporaryFile.r4j2XW.swift:40:29: error: cannot convert value of type 'Int' to expected element type 'SwiftVersion'
    swiftLanguageVersions: [3, 4]
                            ^
```

## Alamofire Environment

**Alamofire version:**
4.8.1 as well as 4.8.0
**Xcode version:**
10.2 (10E125)
**Swift version:**
Apple Swift version 5.0 (swiftlang-1001.0.69.5 clang-1001.0.46.3)
Target: x86_64-apple-darwin18.2.0
**Platform(s) running Alamofire:**
iOS/macOS
**macOS version running Xcode:**
10.14.3

**Comment by beatman423** [comment]
same issue happen to me. need help.

**Comment by ChiellieNL** [comment]
@beatman423 Workaround for now:

Download Xcode 10.1 here: https://developer.apple.com/download/more/
Install and open it, go to preferences and switch Commandline tools back to 10.1
Takes an amount of time and disk usage, but won't block you from working

The guys here are doing a great job btw 👍
It's just Swift that keeps changing their package description continuously without backward compatibility.. *sigh*

**Comment by rex-remind101** [comment]
This file should fix it https://github.com/Alamofire/Alamofire/blob/master/Package%40swift-4.2.swift

A hotfix could help :)

**Comment by jshier** [comment]
A hotfix has been merged to our `hotfix` branch and we'll release it later this week. Target that branch in the mean time. I'll leave this issue open until then.

**Comment by ChiellieNL** [comment]
Thanks for the quick response Jon!

(although you probably already new) I can confirm 
`.package(url: "https://github.com/Alamofire/Alamofire.git", .branch("hotfix"))`
fixes this issue for me 👍

**Comment by Link913** [comment]
👍

**Comment by jshier** [comment]
4.8.2 has been released with this fix. Thanks!

**Comment by ghowen** [comment]
I am still getting this error in a project (https://github.com/LiveUI/Awesome/issues/42) as

        .package(url: "https://github.com/Alamofire/Alamofire.git", from: "4.0.0"),

still pulls 4.8.1.
