### ISSUE TITLE
error: module Alamofire was not compiled for testing (similar issue to #652)

### ISSUE THREAD

**Issue by Reckonian** [Alamofire/Alamofire#1175]
If you carthage update on the latest version of the 3.3 branch you will get error included:

*** Building scheme "Alamofire iOS" in Alamofire.xcworkspace
*** Building scheme "Alamofire OSX" in Alamofire.xcworkspace
** BUILD FAILED **

The following build commands failed:
	CompileSwift normal x86_64 /Carthage/Checkouts/Alamofire/Tests/MultipartFormDataTests.swift
	CompileSwift normal x86_64 /Carthage/Checkouts/Alamofire/Tests/ServerTrustPolicyTests.swift
	CompileSwift normal x86_64 /Carthage/Checkouts/Alamofire/Tests/CacheTests.swift
	CompileSwift normal x86_64 /Carthage/Checkouts/Alamofire/Tests/SessionDelegateTests.swift
	CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
(5 failures)
/Carthage/Checkouts/Alamofire/Tests/SessionDelegateTests.swift:23:18: error: module 'Alamofire' was not compiled for testing
/Carthage/Checkouts/Alamofire/Tests/ResultTests.swift:23:18: error: module 'Alamofire' was not compiled for testing
/Carthage/Checkouts/Alamofire/Tests/ManagerTests.swift:23:18: error: module 'Alamofire' was not compiled for testing
/Carthage/Checkouts/Alamofire/Tests/ValidationTests.swift:23:18: error: module 'Alamofire' was not compiled for testing
/Carthage/Checkouts/Alamofire/Tests/NetworkReachabilityManagerTests.swift:23:18: error: module 'Alamofire' was not compiled for testing
/Carthage/Checkouts/Alamofire/Tests/SessionDelegateTests.swift:23:18: error: module 'Alamofire' was not compiled for testing
/Carthage/Checkouts/Alamofire/Tests/ResultTests.swift:23:18: error: module 'Alamofire' was not compiled for testing
/Carthage/Checkouts/Alamofire/Tests/ManagerTests.swift:23:18: error: module 'Alamofire' was not compiled for testing
/Carthage/Checkouts/Alamofire/Tests/ValidationTests.swift:23:18: error: module 'Alamofire' was not compiled for testing
/Carthage/Checkouts/Alamofire/Tests/NetworkReachabilityManagerTests.swift:23:18: error: module 'Alamofire' was not compiled for testing
/Carthage/Checkouts/Alamofire/Tests/SessionDelegateTests.swift:23:18: error: module 'Alamofire' was not compiled for testing
/Carthage/Checkouts/Alamofire/Tests/ResultTests.swift:23:18: error: module 'Alamofire' was not compiled for testing
/Carthage/Checkouts/Alamofire/Tests/ManagerTests.swift:23:18: error: module 'Alamofire' was not compiled for testing
/Carthage/Checkouts/Alamofire/Tests/ValidationTests.swift:23:18: error: module 'Alamofire' was not compiled for testing
/Carthage/Checkouts/Alamofire/Tests/NetworkReachabilityManagerTests.swift:23:18: error: module 'Alamofire' was not compiled for testing
/Carthage/Checkouts/Alamofire/Tests/SessionDelegateTests.swift:23:18: error: module 'Alamofire' was not compiled for testing
/Carthage/Checkouts/Alamofire/Tests/ResultTests.swift:23:18: error: module 'Alamofire' was not compiled for testing
/Carthage/Checkouts/Alamofire/Tests/ManagerTests.swift:23:18: error: module 'Alamofire' was not compiled for testing
/Carthage/Checkouts/Alamofire/Tests/ValidationTests.swift:23:18: error: module 'Alamofire' was not compiled for testing
/Carthage/Checkouts/Alamofire/Tests/NetworkReachabilityManagerTests.swift:23:18: error: module 'Alamofire' was not compiled for testing

**Comment by cnoon** [comment]
First make sure you're running the latest version of Carthage and Xcode 7.3. Also make sure you're `xcodebuild` is updated to 7.3. Then you need to clean the project, wipe derived data and possibly the Xcode cache. If you're still seeing issues, reboot. After all this, you will see that Alamofire 3.3.0 and 3.3.1 do compile successfully with Xcode 7.3. 

> It will not compile with Xcode 7.2.1 and below.

Cheers. 🍻
