### ISSUE TITLE
Xcode 8 GM - Alamofire 3.5 - Linker command failed

### ISSUE THREAD

**Issue by andre991** [Alamofire/Alamofire#1479]
Hi I using the branch swift3 to use with Swift 3.0 but today now appear Build Failed in carthage update.
```

** BUILD FAILED **


The following build commands failed:
	CompileSwift normal arm64
	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
(2 failures)
/Users/andre/Documents/**App/Carthage/Checkouts/Alamofire/Source/SessionDelegate.swift:198:15: warning: instance method 'urlSession(_:didReceive:completionHandler:)' nearly matches optional requirement 'urlSession(_:didReceive:completionHandler:)' of protocol 'URLSessionDelegate'
/Users/andre/Documents/**App/Carthage/Checkouts/Alamofire/Source/SessionManager.swift:353:24: error: closure use of non-escaping parameter 'destination' may allow it to escape
/Users/andre/Documents/**App/Carthage/Checkouts/Alamofire/Source/TaskDelegate.swift:199:10: warning: instance method 'urlSession(_:dataTask:didReceive:completionHandler:)' nearly matches optional requirement 'urlSession(_:dataTask:didReceive:completionHandler:)' of protocol 'URLSessionDataDelegate'
/Users/andre/Documents/**App/Carthage/Checkouts/Alamofire/Source/TaskDelegate.swift:251:10: warning: instance method 'urlSession(_:dataTask:willCacheResponse:completionHandler:)' nearly matches optional requirement 'urlSession(_:dataTask:willCacheResponse:completionHandler:)' of protocol 'URLSessionDataDelegate'
/Users/andre/Documents/**App/Carthage/Checkouts/Alamofire/Source/Validation.swift:54:44: error: closure use of non-escaping parameter 'validation' may allow it to escape
A shell task failed with exit code 65:
** BUILD FAILED **


The following build commands failed:
	CompileSwift normal arm64
	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
(2 failures)
```
I change to Alamofire 3.5 and carthage update again, but to build project the xcode show this error.(Sorry for my english)

```
/Users/andre/Documents/**App/Carthage/Build/iOS/Alamofire.framework/Alamofire compiled with older version of Swift language (2.0) than previous files (3.0) for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by jshier** [comment]
Alamofire 3.5.0 only supports Swift 2.2 and 2.3. We are working on a 4.0 release which will support Swift 3. In the meantime, for Swift 3, use the `master` branch.
