### ISSUE TITLE
Alamofire 4.9.0 swift version issue

### ISSUE THREAD

**Issue by CyberMew** [Alamofire/Alamofire#2950]
> ℹ Please fill out this template when filing an issue.
> All lines beginning with an ℹ symbol instruct you with what info we expect. You can delete those lines once you've filled in the info.
>
> Per our [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md), we use GitHub for
> bugs and feature requests, not general support. Other issues should be opened on Stack Overflow with the tag `alamofire`.
>
> Please remove this line and everything above it before submitting.

* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## What did you do?

Updated 4.5.1 to 4.9.0.

## What did you expect to happen?

Compiles with Xcode 10.1 as per normal with Swift 4.x

## What happened instead?

Compilation failed, as Swift 5 is required. Changelog for 4.8.0 only mentions updating of project to Swift 4(.2). 4.9.0 did not mention anything. Currently trying to upgrade to Xcode 10.3 and see if it resolves the 'problem'.

## Alamofire Environment

**Alamofire version:** 4.9.0
**Xcode version:** 10.1
**Swift version:** 4.X
**Platform(s) running Alamofire:**
**macOS version running Xcode:** 10.14

## Demo Project

N/A

**Comment by jshier** [comment]
Could you be more specific? What issues are you seeing?

**Comment by jshier** [comment]
Building under 10.1 works just fine. If you have more specific issues, please report them and we can investigate.

**Comment by CyberMew** [comment]
Upgraded to 10.3 and it worked fine. Could be a cocoa pods issue that was resolved by updating it together with Xcode. The original error was something about cannot compile 5.1 Swift for alamofire. We are using Xcode build to build and export.

**Comment by jshier** [comment]
Perhaps you did an integration using Xcode 11, which chose 5.1 as the language version. Or an older version of CocoaPods which chose the last item in the versions array.

**Comment by CyberMew** [comment]
Not possible at all that we were using Xcode11, but I think we were on cocoa pods 1.7.2. 

Anyway, we are on Xcode 10.3 and cocoa pods 1.8.0 and all is fine now.
